# Training parameters
save_dir: "saved_models_MIL4"
plot_dir: "plots"
pretrained_model_dir: "pretrained_models"
attention_branches: [1, 2, 4, 8]
num_epochs: 10
num_folds: 10
batch_size_train: 15
batch_size_test: 25
learning_rate: 0.001
dropout: 0.3
weight_decay: 0.001

# Data paths
data_dir: "data"
model_targets: "data/model_targets.csv"
model_images: "data/model_images.csv"


resolution: 224
transforms:
  normalize:
    mean: [0.4850, 0.4560, 0.4060]
    std: [0.2290, 0.2240, 0.2250]