# Training parameters

# file paths
save_dir: "results"
plot_dir: "plots"
pretrained_model_dir: "../Achilles_MIL/test1-1/cvmodel1.ckpt"
data_dir: "../Achilles_Classification/roi_data"
train_csv: "../Achilles_MIL/test1-1/fold1_train.csv"
val_csv: "../Achilles_MIL/test1-1/fold1_val.csv"
     
# data loading
loader_kwargs:
    batch_size: 15 
    num_workers: 1
res: 224 # height and width
    
# model
net_kwargs:
    pretrained: False
    num_heads: 8
    num_out: 1
    pooling_method: 'attn'
    drop_rate: 0.0
    debug: False

# training
num_epochs: 50
optim_kwargs:
    lr: 1.e-3
    weight_decay: 1.e-3
sched_kwargs:
    step_size: 80
    gamma: 0.25
early_stopper_kwargs:
    patience: 10
verbose: False